matrix:
  include:
    - language: node_js
      script: npm run test
      env:
        - NAME=Jest
      before_install:
        - npm i -g jest-cli
      install:
        - npm install
      node_js:
        - 8
    - language: objective-c
      env:
        - NAME=iOS-11_iPhone-7_arm64
      os: osx
      osx_image: xcode9.4
      script:
        - brew update
        - brew install nvm
        - nvm install 8.4.0
        - npm install
        - cd ios && set -o pipefail xcodebuild -scheme Buttercup -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' build test | xcpretty -c
    - language: objective-c
      env:
        - NAME=iOS-10_iPhone-5_armv7s
      os: osx
      osx_image: xcode9.4
      script:
        - brew update
        - brew install nvm
        - nvm install 8.4.0
        - npm install
        - cd ios && set -o pipefail xcodebuild -scheme Buttercup -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.3' build test | xcpretty -c
    - language: android
      sudo: required
      jdk: oraclejdk8
      env:
        - NAME=Android-23-ARMv7
        - ANDROID_TARGET=android-23
        - ANDROID_API=23
        - ANDROID_ABI=armeabi-v7a
        - ANDROID_BUILD_TOOLS=23.0.1
        - ANDROID_ABI=armeabi-v7a
        - ANDROID_TAG=google_apis
        - ADB_INSTALL_TIMEOUT=5 # minutes
      android:
        components:
          - tools
          - platform-tools
          - build-tools-$ANDROID_BUILD_TOOLS
          - android-$ANDROID_API
          - extra-android-support
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - sys-img-$ANDROID_ABI-$ANDROID_TAG-$ANDROID_API
      before_script:
        - echo "y" | android update sdk -a --no-ui --filter $ANDROID_TARGET
        - echo "y" | android update sdk -a --no-ui --filter sys-img-$ANDROID_ABI-$ANDROID_TAG-$ANDROID_API
        - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --tag $ANDROID_TAG
        - QEMU_AUDIO_DRV=none emulator -avd test -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - npm install
      script:
        - cd android && ./gradlew assemble && cd ..
        - ./scripts/testAndroid.sh
