[package]
name = "crypto"
version = "0.1.0"
authors = ["Sallar Kaboli <sallar.kaboli@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
# buttercup-crypto = "0.1.0"
buttercup-crypto = { path = "../../buttercup-crypto" }
hex = "^0.3"
base64 = "^0.5"
